In [3]:
import pandas as pd

In [4]:
filePath = "input/test.csv"

In [5]:
data = pd.read_csv(filePath)

data.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [7]:
data.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [11]:
data = data.dropna(axis = 0) # dropping all with NA values

In [12]:
data.describe()

       PassengerId     Pclass        Age      SibSp      Parch        Fare
count    87.000000  87.000000  87.000000  87.000000  87.000000   87.000000
mean   1102.712644   1.137931  39.247126   0.597701   0.482759   98.109198
std     126.751901   0.435954  15.218730   0.637214   0.860801   88.177319
min     904.000000   1.000000   1.000000   0.000000   0.000000    0.000000
25%     986.000000   1.000000  27.000000   0.000000   0.000000   35.339600
50%    1094.000000   1.000000  39.000000   1.000000   0.000000   71.283300
75%    1216.000000   1.000000  50.000000   1.000000   1.000000  135.066650
max    1306.000000   3.000000  76.000000   3.000000   4.000000  512.329200

In [13]:
data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
12,904,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,B45,S
14,906,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S
24,916,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
26,918,1,"Ostby, Miss. Helene Ragnhild",female,22.0,0,1,113509,61.9792,B36,C
28,920,1,"Brady, Mr. John Bertram",male,41.0,0,0,113054,30.5000,A21,S

In [14]:
data_features = ["Pclass", "Sex", "Fare", "SibSp", "Parch", "Cabin"]
new_data = data[data_features]

In [15]:
new_data.describe()

          Pclass        Fare      SibSp      Parch
count  87.000000   87.000000  87.000000  87.000000
mean    1.137931   98.109198   0.597701   0.482759
std     0.435954   88.177319   0.637214   0.860801
min     1.000000    0.000000   0.000000   0.000000
25%     1.000000   35.339600   0.000000   0.000000
50%     1.000000   71.283300   1.000000   0.000000
75%     1.000000  135.066650   1.000000   1.000000
max     3.000000  512.329200   3.000000   4.000000